apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k3rdp

resources:
  - namespace.yaml
  - x11rdp-deployment.yaml
  - x11rdp-service-rdp.yaml
  - x11rdp-service-vnc.yaml
  - x11rdp-service-display.yaml
  - qtapp-deployment.yaml
